/**
 * Builds responsive srcset strings for images in public/images/airbnb/.
 *
 * Given a path like "/images/airbnb/photo.jpeg", generates entries like:
 *   "/images/airbnb/photo-400w.jpeg 400w, /images/airbnb/photo-800w.jpeg 800w, ..."
 *
 * Relies on resized JPEG + WebP variants pre-generated by
 * scripts/optimize-images.mjs.
 */

const SIZE_LABELS = ['400w', '800w', '1200w'];

export function buildSrcSet(src: string): string {
  const base = src.replace(/\.(jpe?g)$/i, '');
  const ext = src.match(/\.(jpe?g)$/i)?.[0] || '.jpeg';

  const parts = SIZE_LABELS.map((label) => `${base}-${label}${ext} ${label}`);
  parts.push(`${src} 1200w`);
  return parts.join(', ');
}

/** Builds a responsive WebP srcset for a given JPEG path. */
export function buildWebpSrcSet(src: string): string {
  const base = src.replace(/\.(jpe?g)$/i, '');

  const parts = SIZE_LABELS.map((label) => `${base}-${label}.webp ${label}`);
  parts.push(`${base}.webp 1200w`);
  return parts.join(', ');
}

/** Returns the full-size WebP path for a given JPEG path. */
export function webpSrc(src: string): string {
  return src.replace(/\.(jpe?g)$/i, '.webp');
}
